---
title: "Workshop 6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#functions about spatial clustering
```

```{r library}
#first library a few packages that we will use during the practical
#note you may need to install them first...
install.packages("spatstat")
library(spatstat)
library(here)
library(sp)
library(rgeos)
library(maptools)
library(GISTools)
library(tmap)
library(sf)
library(geojson)
library(geojsonio)
library(tmaptools)
```

```{r 6.5 Setting up your data}
##First, get the London Borough Boundaries
LondonBoroughs <-st_read("/Users/xingyuzhao/Documents/T1/CASA0005 GIS/Workshops/Workshop1_Review/statistical-gis-boundaries-london/ESRI/London_Borough_Excluding_MHW.shp")

# Or use this to read in directly.
#LondonBoroughs <- st_read("https://opendata.arcgis.com/datasets/8edafbe3276d4b56aec60991cbddda50_4.geojson")

```
```{r }
library(stringr) #sre_detect()
BoroughMap <- LondonBoroughs %>%
  dplyr::filter(str_detect(GSS_CODE, "^E09"))%>% #filter -- dplyr
  st_transform(., 27700)

qtm(BoroughMap) #如果用plot会同时画出name，gss_code, hectares, nonld_area, ons_inner和sub_2009

summary(BoroughMap)
```
```{r get the location of all Blue Plaques in the City}
##Now get the location of all Blue Plaques in the City
BluePlaques <- st_read #蓝色徽章 ("https://s3.eu-west-2.amazonaws.com/openplaques/open-plaques-london-2018-04-08.geojson")

BluePlaques <- st_read(here::here("prac6_data",                     "open-plaques-london-2018-04-08.geojson")) %>%
  st_transform(.,27700)

#BluePlaques画不出来，是几个点长方形什么的
```

```{r plot}
#plot the blue plaques in the city
tmap_mode("plot")
## tmap mode set to plotting
tm_shape(BoroughMap) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaques) +
  tm_dots(col = "blue")
#其实不知道为什么geojson

```
```{r 6.5.1 Data cleaning}
#至少有一个Blue Plaque是在伦敦区图外面的，属于errant value会影响我们的分析
#remove duplicates
library(tidyverse)

library(sf)
BluePlaques <- distinct(BluePlaques)
```

```{r 6.5.2 Spatial subsetting构造子集}
#去掉伦敦区图外的点！！！！没见过的code
BluePlaquesSub <- BluePlaques[BoroughMap,]
#check to see that they've been removed
tmap_mode("plot")
tm_shape(BoroughMap) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaquesSub) +
  tm_dots(col = "blue")
```

```{r 6.5.3 Study area}
#只截取出Harrow这一个地方
#extract the borough

Harrow <- BoroughMap %>%
  filter(., NAME=="Harrow")

#Check to see that the correct borough has been pulled out
tm_shape(Harrow) +
  tm_polygons(col = NA, alpha = 0.5)
```

```{r clip the data}
#只做Harrow的图和数据 数据也要只截取Harrow这个地方
#clip the data to our single borough
BluePlaquesSub <- BluePlaques[Harrow,]
#check that it's worked
tmap_mode("plot")
tm_shape(Harrow) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaquesSub) +
  tm_dots(col = "blue")

```
```{r set a window}
#now set a window as the borough boundary
window <- as.owin(Harrow)
plot(window)

#create a sp object
BluePlaquesSub<- BluePlaquesSub %>%
  as(., 'Spatial')
#create a ppp object
BluePlaquesSub.ppp <- ppp(x=BluePlaquesSub@coords[,1],
                          y=BluePlaquesSub@coords[,2],
                          window=window)
```
```{r}
#see what code is doing above
BluePlaquesSub@coords[,1]

BluePlaquesSub.ppp %>%
  plot(.,pch=16,cex=0.5, #pch是指点的样子
       main="Blue Plaques Harrow")

```

```{r 6.6 Point pattern analysis}
#{r Kernel Density Estimation}

#density map
BluePlaquesSub.ppp %>%
  density(., sigma=500) %>%  #在这张图中sigma越大红色部分越多
  plot()

#density map
BluePlaquesSub.ppp %>%
  density(., sigma=1000) %>%  #在这张图中sigma越大红色部分越多
  plot()
```
```{r 6.6.2 Quadrat Analysis}
#First plot the points
plot(BluePlaquesSub.ppp,
     pch=16,
     cex=0.5, 
     main="Blue Plaques in Harrow")

#now count the points in that fall in a 6 x 6
#grid overlaid across the windowBluePlaquesSub.ppp2<-BluePlaquesSub.ppp %>%
BluePlaquesSub.ppp %>%
  quadratcount(.,nx = 6, ny = 6)%>% #创建6*6表格
    plot(., add=T, col="red")
```
```{r}
#run the quadrat count
Qcount <- BluePlaquesSub.ppp %>%
  quadratcount(.,nx = 6, ny = 6) %>%
  as.data.frame() %>%
  dplyr::count(Var1=Freq)%>%
  dplyr::rename(Freqquadratcount=n)  
  
Qcount %>% 
  summarise_all(class)
```
```{r}
sums <- Qcount %>%
  #calculate the total blue plaques (Var * Freq)
  mutate(total = Var1 * Freqquadratcount) %>%
  dplyr::summarise(across(everything(), sum))%>%
  dplyr::select(-Var1) 

lambda<- Qcount%>%
  #calculate lambda
  mutate(total = Var1 * Freqquadratcount)%>%
  dplyr::summarise(across(everything(), sum)) %>%
  mutate(lambda=total/Freqquadratcount) %>%
  dplyr::select(lambda)%>%
  pull(lambda)
```

```{r}
QCountTable <- Qcount %>%
  mutate(Pr=((lambda^Var1)*exp(-lambda))/factorial(Var1))%>%
  #now calculate the expected counts based on our total number of plaques
  #and save them to the table
  #不懂
  mutate(Expected= (round(Pr * sums$Freqquadratcount, 0)))

#Compare the frequency distributions of the observed and expected point patterns
plot(c(1,5),c(0,14), type="n",
xlab="Number of Blue Plaques (Red=Observed,Blue=Expected)", 
     ylab="Frequency of Occurances")
points(QCountTable$Freqquadratcount, 
       col="Red", 
       type="o", 
       lwd=3)
points(QCountTable$Expected, col="Blue", 
       type="o", 
       lwd=3)
```

```{r}
teststats <- quadrat.test(BluePlaquesSub.ppp, nx = 6, ny = 6)

plot(BluePlaquesSub.ppp,pch=16,cex=0.5, main="Blue Plaques in Harrow")
plot(teststats, add=T, col = "red")
```

```{r Chi value}
#the higher the Chi-Squared value, the greater the difference
teststats <- quadrat.test(BluePlaquesSub.ppp, nx = 6, ny = 6)

plot(BluePlaquesSub.ppp,pch=16,cex=0.5, main="Blue Plaques in Harrow")
plot(teststats, add=T, col = "red")
```

```{r 6.6.4 Ripley's K}
K <- BluePlaquesSub.ppp %>%
  Kest(., correction="border") %>%
  plot()

Kval <- as.data.frame(Kest(BluePlaquesSub.ppp, correction = "border"))
```

```{r 6.7 DBSCAN}
#Ripley's K的局限是无法知道哪里会有clusters，
#DBSCAN用来寻找空间中的clusters


